🎯 Novo desafio: Sistema de notas escolares
Imagine que você tem uma turma de alunos e precisa montar uma tabela de desempenho, como se fosse uma “classificação” igual ao campeonato.

O que você deve implementar:
Média de notas → cada aluno tem notas em várias provas.

Situação final → aprovado se média ≥ 7, recuperação se média entre 5 e 6.9, reprovado se < 5.

Ranking de desempenho → ordenar os alunos pela média, como se fosse uma tabela de classificação.

Coluna de faltas → se quiser complicar, adicione faltas e defina reprovação por excesso de faltas.

In [28]:
import pandas as pd
import numpy as np

In [29]:
alunos = {'alunos':['FELIPE', 'AMANDA', 'LEONARNDO', 'EDUARDO', 'MIGUEL', 'MARIA EDUARDA', 'LARISSA', 'HUGO', 'EDMAR', 'SANDRA', 'CONCEIÇÃO', 'MARIA CLARA'],'TRABALHO':[7,10,6,8,5,4,3,2,7,4,2,6],'TAREFAS':[10,9,7,6,6,5,4,3,5,4,2,3],'PROVA':[9,8,9,7,8,6,5,4,3,2,3,1]}

In [30]:
sala_aula = pd.DataFrame(alunos)

In [31]:
sala_aula

           alunos  TRABALHO  TAREFAS  PROVA
0          FELIPE         7       10      9
1          AMANDA        10        9      8
2       LEONARNDO         6        7      9
3         EDUARDO         8        6      7
4          MIGUEL         5        6      8
5   MARIA EDUARDA         4        5      6
6         LARISSA         3        4      5
7            HUGO         2        3      4
8           EDMAR         7        5      3
9          SANDRA         4        4      2
10      CONCEIÇÃO         2        2      3
11    MARIA CLARA         6        3      1

In [32]:
sala_aula['menor nota'] = sala_aula[['TRABALHO', 'TAREFAS','PROVA']].min(axis=1)

In [33]:
sala_aula['SITUAÇÃO'] = sala_aula['menor nota'].apply( lambda x: 'REPROVADO' if x < 6 else ('RECUPERAÇÃO' if x < 7 else 'APROVADO'))

In [34]:
sala_aula

           alunos  TRABALHO  TAREFAS  PROVA  menor nota     SITUAÇÃO
0          FELIPE         7       10      9           7     APROVADO
1          AMANDA        10        9      8           8     APROVADO
2       LEONARNDO         6        7      9           6  RECUPERAÇÃO
3         EDUARDO         8        6      7           6  RECUPERAÇÃO
4          MIGUEL         5        6      8           5    REPROVADO
5   MARIA EDUARDA         4        5      6           4    REPROVADO
6         LARISSA         3        4      5           3    REPROVADO
7            HUGO         2        3      4           2    REPROVADO
8           EDMAR         7        5      3           3    REPROVADO
9          SANDRA         4        4      2           2    REPROVADO
10      CONCEIÇÃO         2        2      3           2    REPROVADO
11    MARIA CLARA         6        3      1           1    REPROVADO