In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {'SEDE':['SP','SP','MG','MG','RJ','RJ','ES','ES'],'VENDEDOR':['JORGE','ANA','THIAGO','PEDRO','RAFAEL','GUTO','MARIA','CAROL'],'VENDAS':[2000,2500,3100,1200,1500,3900,2900,3900]}
df = pd.DataFrame(data)

In [4]:
arrays = [['SÃO PAULO','SÃO PAULO','RIO DE JANEIRO', 'RIO DE JANEIRO', 'MINAS GERAIS', 'MINAS GERAIS'],['GARRAFAS','COPOS','GARRAFAS','COPOS','GARRAFAS','COPOS']]
index = pd.MultiIndex.from_arrays(arrays, names=('ESTADO','PRODUTO'))

In [6]:
df1 = pd.DataFrame({'TOTAL VENDIDO R$':[10000,35000,22400,12890,10880,13900]},index=index)

In [7]:
df

  SEDE VENDEDOR  VENDAS
0   SP    JORGE    2000
1   SP      ANA    2500
2   MG   THIAGO    3100
3   MG    PEDRO    1200
4   RJ   RAFAEL    1500
5   RJ     GUTO    3900
6   ES    MARIA    2900
7   ES    CAROL    3900

In [9]:
df.groupby('SEDE')

In [10]:
by_Sede = df.groupby('SEDE')

In [11]:
by_Sede.max()

     VENDEDOR  VENDAS
SEDE
ES      MARIA    3900
MG     THIAGO    3100
RJ     RAFAEL    3900
SP      JORGE    2500

In [19]:
by_Sede.min()

     VENDEDOR  VENDAS
SEDE
ES      CAROL    2900
MG      PEDRO    1200
RJ       GUTO    1500
SP        ANA    2000

In [20]:
df

  SEDE VENDEDOR  VENDAS
0   SP    JORGE    2000
1   SP      ANA    2500
2   MG   THIAGO    3100
3   MG    PEDRO    1200
4   RJ   RAFAEL    1500
5   RJ     GUTO    3900
6   ES    MARIA    2900
7   ES    CAROL    3900

In [21]:
df1

                         TOTAL VENDIDO R$
ESTADO         PRODUTO
SÃO PAULO      GARRAFAS             10000
               COPOS                35000
RIO DE JANEIRO GARRAFAS             22400
               COPOS                12890
MINAS GERAIS   GARRAFAS             10880
               COPOS                13900