In [1]:
import pandas as pd
import numpy as np

In [7]:
lista = [['BRASIL', 'BRASIL', 'BRASIL', 'EUA','EUA', 'EUA'],[2017,2018,20119,2017,2018,2019]]

In [8]:
tuplas = zip(*lista)

In [9]:
tuplas

In [10]:
tuplas = list(tuplas)

In [11]:
tuplas

[('BRASIL', 2017),
 ('BRASIL', 2018),
 ('BRASIL', 20119),
 ('EUA', 2017),
 ('EUA', 2018),
 ('EUA', 2019)]

In [12]:
multi = pd.MultiIndex.from_tuples(tuplas)

In [13]:
multi

MultiIndex([('BRASIL',  2017),
            ('BRASIL',  2018),
            ('BRASIL', 20119),
            (   'EUA',  2017),
            (   'EUA',  2018),
            (   'EUA',  2019)],
           )

In [14]:
df1 = pd.DataFrame(data = np.random.randn(6,2), index=multi,columns = ['EXPO TRIGO', 'EXPO ARROZ'])

In [15]:
df1

              EXPO TRIGO  EXPO ARROZ
BRASIL 2017     1.475446    0.603525
       2018    -1.057828   -0.017490
       20119    0.399537    2.063733
EUA    2017     0.542486   -0.158010
       2018    -0.335425   -2.242928
       2019    -0.658726   -0.688976

In [16]:
df1.index.names = ['PAÍS', 'ANO']

In [17]:
df1

              EXPO TRIGO  EXPO ARROZ
PAÍS   ANO
BRASIL 2017     1.475446    0.603525
       2018    -1.057828   -0.017490
       20119    0.399537    2.063733
EUA    2017     0.542486   -0.158010
       2018    -0.335425   -2.242928
       2019    -0.658726   -0.688976

In [18]:
# ENCONTRANDO VALORES

In [19]:
df1['EXPO ARROZ']

PAÍS    ANO
BRASIL  2017     0.603525
        2018    -0.017490
        20119    2.063733
EUA     2017    -0.158010
        2018    -2.242928
        2019    -0.688976
Name: EXPO ARROZ, dtype: float64

In [20]:
df1.loc['BRASIL']

       EXPO TRIGO  EXPO ARROZ
ANO
2017     1.475446    0.603525
2018    -1.057828   -0.017490
20119    0.399537    2.063733

In [21]:
# PARA PEGAR UM NIVEL EXEMPLO 2017 PARA IMPRIMIR NA TELA
df1.xs(2017, level=1)

        EXPO TRIGO  EXPO ARROZ
PAÍS
BRASIL    1.475446    0.603525
EUA       0.542486   -0.158010

In [22]:
df1[:2]

             EXPO TRIGO  EXPO ARROZ
PAÍS   ANO
BRASIL 2017    1.475446    0.603525
       2018   -1.057828   -0.017490

In [24]:
# VENDO O DF DE OUTRA MANEIRA

In [25]:
df1.unstack()

       EXPO TRIGO                               EXPO ARROZ            \
ANO         2017      2018      2019      20119      2017      2018
PAÍS
BRASIL   1.475446 -1.057828       NaN  0.399537   0.603525 -0.017490
EUA      0.542486 -0.335425 -0.658726       NaN  -0.158010 -2.242928


ANO        2019      20119
PAÍS
BRASIL       NaN  2.063733
EUA    -0.688976       NaN