# MERGE / JOIN / CONCATENATE

In [2]:
# CONCATENATE -> melhor utilizado quando temos colunas com nomes iguais, melhor utilizado na vertical
# MERGE / JOIN -> horizontal ultilizando o HOW passando onde unir (left, inner, outer, right)
# outer -> junta todos os que nao tem valor ele deixa NULO, inner junta apenas que tem em ambas tabelas

In [3]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']},index=[0,1,2,3])

In [5]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],'B':['B4','B5','B6','B7'],'C':['C4','C5','C6','C7'],'D':['D4','D5','D6','D7']}, index=[4,5,6,7])

In [6]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],'B':['B8','B9','B10','B11'],'C':['C8','C9','C10','C11'],'D':['D8','D9','D10','D11']},index=[8,9,10,11])

In [7]:
dicionario = {'ID':[10,11,12,13,14],'NOME':['Maria','Joana','Claudia','Lucas','Gabriel'],'CIDADE':['SP','RJ','SP','CP','SC']}

In [8]:
dicionario2 = {'ID':[16,11,12,13,18],'EXPERIENCIA':['junior','senior','pleno','estagiario','analista']}

In [11]:
df4 = pd.DataFrame(data=dicionario)
df5 = pd.DataFrame(data=dicionario2)

In [12]:
#cocatenar

In [13]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [14]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [15]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [18]:
df_concat = pd.concat([df1,df2,df3])

In [19]:
df_concat

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [20]:
# MERGE

In [21]:
df4

   ID     NOME CIDADE
0  10    Maria     SP
1  11    Joana     RJ
2  12  Claudia     SP
3  13    Lucas     CP
4  14  Gabriel     SC

In [22]:
df5

   ID EXPERIENCIA
0  16      junior
1  11      senior
2  12       pleno
3  13  estagiario
4  18    analista

In [23]:
#merge // inner lembrando que so aparece id iguais

In [24]:
merge_inner = pd.merge(df4,df5)

In [25]:
merge_inner

   ID     NOME CIDADE EXPERIENCIA
0  11    Joana     RJ      senior
1  12  Claudia     SP       pleno
2  13    Lucas     CP  estagiario

In [26]:
# merge outer // lembrando que esse aparece todos , os que nao tem numero aparece nulo

In [27]:
merge_outer = pd.merge(df4,df5, how='outer')

In [28]:
merge_outer

   ID     NOME CIDADE EXPERIENCIA
0  10    Maria     SP         NaN
1  11    Joana     RJ      senior
2  12  Claudia     SP       pleno
3  13    Lucas     CP  estagiario
4  14  Gabriel     SC         NaN
5  16      NaN    NaN      junior
6  18      NaN    NaN    analista

In [29]:
# merge left // esse os valores da esquerda que manda

In [30]:
merge_left = pd.merge(df4,df5,how='left')

In [31]:
merge_left

   ID     NOME CIDADE EXPERIENCIA
0  10    Maria     SP         NaN
1  11    Joana     RJ      senior
2  12  Claudia     SP       pleno
3  13    Lucas     CP  estagiario
4  14  Gabriel     SC         NaN

In [32]:
# merge right // todos os valores da direita que manda

In [33]:
merge_right = pd.merge(df4,df5,how='right')

In [34]:
merge_right

   ID     NOME CIDADE EXPERIENCIA
0  16      NaN    NaN      junior
1  11    Joana     RJ      senior
2  12  Claudia     SP       pleno
3  13    Lucas     CP  estagiario
4  18      NaN    NaN    analista

In [37]:
# join

In [40]:
join_esq = df4.join(df5, lsuffix='_x', rsuffix='Y')

In [41]:
join_esq

   ID_x     NOME CIDADE  IDY EXPERIENCIA
0    10    Maria     SP   16      junior
1    11    Joana     RJ   11      senior
2    12  Claudia     SP   12       pleno
3    13    Lucas     CP   13  estagiario
4    14  Gabriel     SC   18    analista